### ISSUE TITLE
Add lastchanged timestamp to API

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/switchboard#125]
Request from the SSHOC Marketplace developers, with the intention to disply the LRS tools into the Marketplace: adding a timestamp for the last change to the tool description to the API, so that the Marketplace knows when to update existing entries.

**Comment by emanueldima** [comment]
@dietervu I have a few questions: 

1. Which is the source of tools for the SSHOC Marketplace: the Switchboard API (switchboard.clarin.eu/api/tools) or the Github repository (https://github.com/clarin-eric/switchboard-tool-registry/tree/master/tools)? I would say the Github repo should be used, since the Switchboard API does not list some tools (e.g. development tools).

1. In either case, isn't it better to just diff the tool content for detecting changes? A human will surely forget to update an explicit "last_modified" field. I can display the file system's "Last Modified" for each tool, and that seems to give the correct result right now, but this solution seems brittle considering that the files are exposed to Switchboard instances via git and docker volume mounting.

**Comment by kreetrapper** [comment]
I'll reply in Dieter's stead here.
1. We have to ask if that's possible. On a first glance it looks like API is the preferred way to do this. And maybe it's actually a bonus that non-stable tools will not be shown as we might want to exclude them from the marketplace anyway.

2. If all the information comes from the github repo anyway, wouldn't it be possible to simply get the date of the last commit and use that as the "lastchanged" date? Or ist that somehow not possible?

**Comment by andmor-** [comment]
It is possible to get it but it can be misleading due to irrelevant changes (maybe this is still OK anyway). I am not sure what's the best here. This info could also be kept on the Marketplace side.

**Comment by kreetrapper** [comment]
Turns out that the SSHOC marketplace does not need this after all. If there are no other requirements for this from somewhere else, we can close this as "wontfix".

**Comment by emanueldima** [comment]
Ok, closing it for now.
