### ISSUE TITLE
Allow repositories to send multiple files to the switchboard

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#154]
Some tools require multiple files. For instance the Ariadne Visual Media Service takes an 3d model object file that can reference a material file that can reference other texture files. These files can come from a repository like, for instance, the Arachne repo (https://arachne.dainst.org). All these files must be transferred to the Switchboard as part of the same session and matched as a single unit.

**Comment by proycon** [comment]
This is also relevant for CLAM-based webservices (though in practice almost all services we now have work fine with a single input file). CLAM defines 'input templates' and there may be multiple, they may also be either optional or required.

**Comment by emanueldima** [comment]
@proycon Can you give me an example (and maybe docs) of such an input template?

**Comment by proycon** [comment]
Sure, let me give you some CLAM XML describing the PICCL webservice at https://webservices.cls.ru.nl, as an example:

```xml
<profile>
     <input>
        <InputTemplate id="tif" format="TiffImageFormat" label="TIF image of a scanned page (perform OCR)" mimetype="image/tiff" extension="tif" optional="no" unique="no" acceptarchive="no">
        </InputTemplate>
        <InputTemplate id="lexicon" format="PlainTextFormat" label="Custom Lexicon" mimetype="text/plain" filename="lexicon.lst" optional="yes" unique="yes" acceptarchive="no">
            <StaticParameter id="encoding" name="Encoding" description="The character encoding of the file" value="utf-8" />
        </InputTemplate>
    </input>
```

This defines two 'input templates' (i.e. input slots) for the webservice, one to upload a TIFF image, and one to upload a custom lexicon (plain text), the latter is optional here. Right now the switchboard only supports one afaik (which isn't that much of a big deal for now because most of our services work fine with one input slot), but in theory there could be more complex webservices that require or can take multiple inputs. CLAM users on upload have to explicitly denote to for what input template they upload (because technically multiple templates can also carry the same mime-type so that need not be a distinguishing factor).

The generic CLAM documentation for this is at: https://clam.readthedocs.io/en/latest/serviceconfiguration.html#profile-specification , and could perhaps serve for some inspiration. I assume things like swagger/OpenAPI have similar facilities to express multiple inputs.
